name: Create Mirror Issue

on:
  repository_dispatch:
    types: [mirror]

jobs:
  mirror-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Generate JWT Token
        id: generate-jwt
        uses: PalmEmanuel/PSConfEU2025-Core/.github/actions/create-jwt@demo-2
        with:
          clientId: ${{ secrets.GH_APP_CLIENT_ID }}
          privateKey: ${{ secrets.GH_APP_PRIVATE_KEY }}
        
      - name: Get Installation Token
        id: get-installation-token
        uses: PalmEmanuel/PSConfEU2025-Core/.github/actions/create-installation-token@demo-2
        with:
          account: ${{ github.repository_owner }}
          jwt: ${{ steps.generate-jwt.outputs.token }}
    
      - name: Create Mirror Issue
        id: create-mirror-issue
        shell: pwsh
        env:
          SOURCE_ISSUE_LINK: ${{ github.event.client_payload.issue_link }}
          TOKEN: ${{ steps.get-installation-token.outputs.token }}
        run: |
          $Headers = @{
              Authorization = "Bearer ${{ env.TOKEN }}"
          }

          $IssueBody = @{
              title = $IssueTitle
              body  = @"
          A new issue has been created in the Core repository. Please check it out [here]($($env:SOURCE_ISSUE_LINK)).
          "@
          } | ConvertTo-Json

          $Uri = "https://api.github.com/repos/${{ github.repository }}/issues"

          $IssueResult = Invoke-RestMethod -Uri $Uri -Method Post -Headers $Headers -Body $IssueBody -ContentType 'application/json'

          Add-Content -Path $env:GITHUB_ENV -Value "issueLink=$($IssueResult.html_url)"

      - name: Comment on Original Issue
        uses: PalmEmanuel/PSConfEU2025-Core/.github/actions/comment-issue@demo-2
        env:
          ISSUE_LINK: ${{ steps.create-mirror-issue.outputs.issueLink }}
        with:
          token: ${{ steps.get-installation-token.outputs.token }}
          issue_number: ${{ github.event.client_payload.issue_number }}
          repository: ${{ github.event.client_payload.source_repo }}
          body: |
            Thanks for opening this issue! :star:
            
            This issue has been mirrored in the internal repository at ${{ env.ISSUE_LINK }} :repeat:

            Have you heard of [PowerShell Conference Europe](https://psconf.eu)? It's a great place to discuss challenges and solutions for PowerShell and related technologies! :computer:

        