name: Create Mirror Issue

# Add trigger

jobs:
  mirror-issue:
    runs-on: ubuntu-latest
    steps:

      # Get Installation Token
      # Copy and modify
    
      - name: Create Mirror Issue
        id: create-mirror-issue
        shell: pwsh
        env:
          SOURCE_ISSUE_LINK: ${{ github.event.client_payload.issue_link }}
          SOURCE_ISSUE_TITLE: ${{ github.event.client_payload.issue_title }}
          TOKEN: ${{ steps.get-installation-token.outputs.token }}
        run: |
          $Headers = @{
              Authorization = "Bearer $($env:TOKEN)"
          }

          $IssueBody = @{
              title = $env:SOURCE_ISSUE_TITLE
              body  = "A new issue has been created in the Core repository. Please check it out at $($env:SOURCE_ISSUE_LINK)."
          } | ConvertTo-Json

          $Uri = "https://api.github.com/repos/${{ github.repository }}/issues"

          $IssueResult = Invoke-RestMethod -Uri $Uri -Method Post -Headers $Headers -Body $IssueBody -ContentType 'application/json'

          # Can also add environment vars instead of output
          Add-Content -Path $env:GITHUB_ENV -Value "issueLink=$($IssueResult.html_url)"

      # Comment on Original Issue
      # Copy and modify
      ## This issue has been mirrored in the internal repository at $($env:issueLink) :repeat:
